
services:
  bot:
    image: ${DOCKER_REGISTRY}tower:${DOCKER_TAG:-latest}
    container_name: bot
    environment:
      - SQL_SERVER_PASSWORD=${SQL_SERVER_PASSWORD}
      - SQL_SERVER_HOST=sqlserver
      - SQL_SERVER_PORT=1433
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    depends_on:
      - sqlserver
    entrypoint: ["./wait-for-it.sh", "sqlserver:1433", "-t", "120", "--", "sh", "-c", "dotnet Tower.dll --environment Production"]
    restart: always
    networks:
      - app-network
    volumes:
      - 'C:\SharedTemp:/tmp'

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_PASSWORD}
    ports:
      - "${SQL_SERVER_PORT:-1433}:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    restart: always
    networks:
      - app-network

volumes:
  sqlvolume:

networks:
  app-network:
    driver: bridge
