# TODO: ${DB_PORT}

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_PASSWORD}
    ports:
      - "5433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - sqlnetwork

volumes:
  sqlvolume:

networks:
  sqlnetwork:
    driver: bridge
