
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot-dev
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - ANTIVIRUS_SERVER_HOST=host.docker.internal
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GOOGLE_SERVICE_ACCOUNT_JSON=${GOOGLE_SERVICE_ACCOUNT_JSON}
    depends_on:
      - sqlserver
    entrypoint: ["./wait-for-it.sh", "sqlserver:1433", "-t", "120", "--", "sh", "-c", "dotnet Tower.dll --environment Development"]
    networks:
      - app-network
    volumes:
      - '/tmp:/tmp'

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-dev
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT:-1433}:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - app-network

volumes:
  sqlvolume:

networks:
  app-network:
    driver: bridge
