
services:
  bot:
    image: ${DOCKER_REGISTRY}tower:${DOCKER_TAG:-latest}
    container_name: bot
    environment:
      - DB_HOST=sqlserver
      - DB_PORT=1433
      - ANTIVIRUS_SERVER_HOST=host.docker.internal
    depends_on:
      - sqlserver
    entrypoint: ["./wait-for-it.sh", "sqlserver:1433", "-t", "120", "--", "sh", "-c", "dotnet Tower.dll --environment Production"]
    restart: always
    networks:
      - app-network
    volumes:
      - 'C:\SharedTemp:/tmp'

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT:-1433}:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    restart: always
    networks:
      - app-network

volumes:
  sqlvolume:

networks:
  app-network:
    driver: bridge
